---
kind: pipeline
type: docker
name: default

steps:
- name: build 
  image: jekyll/jekyll
  commands:
  - bundle install
  - bundle exec jekyll build
  - echo $JEKYLL_ROOTLESS
  environment:
    JEKYLL_ROOTLESS: 1
    JEKYLL_UID: 1000
    JEKYLL_GID: 1000
