---
kind: pipeline
type: docker
name: default

steps:
- name: build 
  image: ruby
  commands:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  environment:
    JEKYLL_ROOTLESS: 1
    JEKYLL_UID: 1000
    JEKYLL_GID: 1000
- name: deploy
  image: drillster/drone-rsync
  settings:
    hosts: [ "galactic" ]
    user: aaditya
    source: _site/*
    target: ~/build
    delete: true
    recursive: true
    key:
      from_secret: rsync_key 
    when:
      event: [ push ] ## Would run only on a push to master
      branch: [ master ] ## Only the master branch can be deployed to production
trigger:
  event:
  - push
  - pull_request
  - tag
  - rollback

