---
kind: pipeline
type: docker
name: default

steps:
- name: build 
  image: ruby
  commands:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  - whoami
  environment:
    JEKYLL_ROOTLESS: 1
    JEKYLL_UID: 1000
    JEKYLL_GID: 1000
- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 192.168.1.51
    username: root
    password:
      from_secret: rsync_key
    port: 22
    target: ~/build
    rm: true
    source: _site/*
trigger:
  event:
  - push
  - pull_request
  - tag
  - rollback

