---
kind: pipeline
type: docker
name: default

steps:
- name: build 
  image: ruby
  commands:
  - gem install bundler
  - bundle install
  - bundle exec jekyll build
  environment:
    JEKYLL_ROOTLESS: 1
    JEKYLL_UID: 1000
    JEKYLL_GID: 1000
