name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Ruby
        run: apt update -y && apt install -y ruby-full
      - name: Compile website with Jekyll
        run: gem install bundler && bundle install && bundle exec jekyll build
      - name: Copy build to host
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "_site"
          target: ${{ secrets.PATH }}