name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Ruby
        run: apt update -y && apt install -y ruby-full
      - name: Compile website with Jekyll
        run: gem install bundler && bundle install && bundle exec jekyll build
      - uses: actions/upload-artifact@v3
        with:
          name: jekyll
          path: _site